export default {
  ADD_PROS_ITEM: 'ADD_PROS_ITEM',
  ADD_CONS_ITEM: 'ADD_CONS_ITEM',
  EDIT_PROS_ITEM: 'EDIT_PROS_ITEM',
  EDIT_CONS_ITEM: 'EDIT_CONS_ITEM',
  REMOVE_PROS_ITEM: 'REMOVE_PROS_ITEM',
  REMOVE_CONS_ITEM: 'REMOVE_CONS_ITEM',
}